# Autogenerated file
MODULE_VERSION = "0.0"
GIT_COMMIT_HASH = "ec80b63fbdd992c44938835f70828479620aec2c"
GIT_REMOTE_URL = (
    "http://jianxuc@stash.corp.alleninstitute.org/scm/aicsad/aics-feature.git"
)
